In [1]:
import pandas
df = pandas.read_csv("/Users/ephre/Downloads/weather_data.csv")
df

         day  temp condition
0     Monday    12     Sunny
1    Tuesday    14      Rain
2  Wednesday    15      Rain
3   Thursday    14    Cloudy
4     Friday    21     Sunny
5   Saturday    22     Sunny
6     Sunday    24     Sunny

In [3]:
df [2:3]

         day  temp condition
2  Wednesday    15      Rain